import type { Metadata } from "next";
import "../../globals.css";
import Navbar from "@/components/page/Navbar";

export const metadata: Metadata = {
    title: "Dev Academy | Profile",
    description: "Generated by create next app",
};

export default function StudentLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <Navbar />
            {children}
        </div>
    );
}
